// Generated by tools/generate-knowledge-map-data.js. Do not edit manually.

export interface GraphNode {
  id: string;
  name: string;
  category: string;
  description: string;
}

export interface GraphLink {
  source: string;
  target: string;
  weight: number;
}

export interface GraphData {
  nodes: GraphNode[];
  links: GraphLink[];
}

export const CATEGORIES = [
  {
    "name": "Agent",
    "color": "#525252"
  },
  {
    "name": "工程实践",
    "color": "#737373"
  }
] as const;

export const graphData: GraphData = {
  "nodes": [
    {
      "id": "node:Harness",
      "name": "Harness",
      "category": "Agent",
      "description": "Harness 是模型之外负责执行的那一层系统：它维持跨回合的上下文、调用工具、约束运行边界、处理审批与失败，并让工作继续推进；模型只在这一层提供的循环里做推理。它不包含模型本身，也不包含模型服务的托管部分。"
    },
    {
      "id": "node:MCP",
      "name": "MCP",
      "category": "Agent",
      "description": "MCP（Model Context Protocol）是一个开放标准，用统一的客户端—服务器协议把 AI 应用连接到外部系统：数据源、工具和工作流由 MCP 服务器暴露，AI 应用通过 MCP 客户端连接并取用。"
    },
    {
      "id": "node:PTC",
      "name": "PTC",
      "category": "Agent",
      "description": "PTC（Programmatic Tool Calling）是一种让模型生成程序、由程序组织多次工具调用和控制流的方法。"
    },
    {
      "id": "node:SSE",
      "name": "SSE",
      "category": "工程实践",
      "description": "一句话定义：SSE（Server-Sent Events）是一种基于 HTTP 的服务器到客户端单向事件流机制，客户端建立连接后，服务器以事件流持续发送数据，客户端不能通过同一 SSE 连接向服务器发送事件。"
    },
    {
      "id": "node:Streamable HTTP",
      "name": "Streamable HTTP",
      "category": "Agent",
      "description": "一句话定义：Streamable HTTP 是 MCP 的一种 HTTP 传输方式：服务器提供同时支持 POST 和 GET 的单一 MCP 端点，客户端通过 POST 发送 JSON-RPC 消息，服务器可返回单个 JSON 对象或使用 SSE 流式返回消息。"
    },
    {
      "id": "node:Tool Calling",
      "name": "Tool Calling",
      "category": "Agent",
      "description": "Tool Calling 是模型选择并调用外部工具、再根据工具结果继续决定后续步骤的交互机制。"
    }
  ],
  "links": [
    {
      "source": "node:Harness",
      "target": "node:Tool Calling",
      "weight": 2
    },
    {
      "source": "node:MCP",
      "target": "node:Streamable HTTP",
      "weight": 2
    },
    {
      "source": "node:MCP",
      "target": "node:Tool Calling",
      "weight": 2
    },
    {
      "source": "node:PTC",
      "target": "node:Tool Calling",
      "weight": 5
    },
    {
      "source": "node:SSE",
      "target": "node:Streamable HTTP",
      "weight": 2
    }
  ]
};
