title: Xinyu Deng's Homepage
page-top-title: Xinyu Deng
top-section-bg-text: Be what you wanna be
home-subtitle: Xinyu Deng&infj;|&ensp;Eleven
copyright-text: '&copy; Xinyu Deng 2023-2025. All Rights Reserved.'
