title: Xinyu Deng's Homepage
page-top-title: Xinyu Deng
top-section-bg-text: Be what you wanna be
home-subtitle: Xinyu Deng | Control Science & Engineering, ZJU
copyright-text: '&copy; Xinyu Deng 2023-2026. All Rights Reserved.'
